openapi: "3.0.0"
info:
  title: E-Commerce API
  version: "1.0.0"
  description: |
    REST API for an e-commerce platform including authentication, users,
    categories, products, and orders.

servers:
  - url: https://itis-4166-e-commerce-final-project-2.onrender.com/api/docs/#/
    description: Production (Render)
  - url: http://localhost:3000/api
    description: Local Development

tags:
  - name: Auth
  - name: Users
  - name: Categories
  - name: Products
  - name: Orders

paths:

  ###########################
  # AUTH
  ###########################
  /auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterInput"
      responses:
        "201":
          description: Successfully registered
        "400":
          description: Email already exists

  /auth/login:
    post:
      tags: [Auth]
      summary: Login a user and receive a JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginInput"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  ###########################
  # USERS
  ###########################
  /users:
    get:
      tags: [Users]
      summary: Get all users (Admin only)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of all users
        "403":
          description: Forbidden

  /users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User found
        "404":
          description: User not found

  ###########################
  # CATEGORIES
  ###########################
  /categories:
    get:
      tags: [Categories]
      summary: Get all categories
      responses:
        "200":
          description: List of categories

    post:
      tags: [Categories]
      summary: Create a category (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryInput"
      responses:
        "201":
          description: Category created
        "403":
          description: Forbidden

  /categories/{id}:
    get:
      tags: [Categories]
      summary: Get category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Category found
        "404":
          description: Not found

    put:
      tags: [Categories]
      summary: Update category (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryInput"
      responses:
        "200":
          description: Category updated
        "404":
          description: Not found

    delete:
      tags: [Categories]
      summary: Delete category (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Category deleted
        "404":
          description: Not found

  ###########################
  # PRODUCTS
  ###########################
  /products:
    get:
      tags: [Products]
      summary: Get all products
      responses:
        "200":
          description: List of products

    post:
      tags: [Products]
      summary: Create product (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Product created

  /products/{id}:
    get:
      tags: [Products]
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Product found
        "404":
          description: Product not found

    put:
      tags: [Products]
      summary: Update product (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Updated product

    delete:
      tags: [Products]
      summary: Delete product (Admin only)
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Product deleted

  ###########################
  # ORDERS
  ###########################
  /orders:
    get:
      tags: [Orders]
      summary: Get orders (Admin gets all, User gets their own)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Orders returned

    post:
      tags: [Orders]
      summary: Create a new order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderInput"
      responses:
        "201":
          description: Order created

  /orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID (Admin or Owner)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Order found
        "404":
          description: Not found

    put:
      tags: [Orders]
      summary: Update an order (Owner only)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Order updated

    delete:
      tags: [Orders]
      summary: Delete order (Admin only)
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Order deleted

#######################################
# COMPONENTS
#######################################
components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    UserRegisterInput:
      type: object
      required: [name, email, password]
      properties:
        name: { type: string }
        email: { type: string }
        password: { type: string }

    UserLoginInput:
      type: object
      required: [email, password]
      properties:
        email: { type: string }
        password: { type: string }

    CategoryInput:
      type: object
      required: [name]
      properties:
        name: { type: string }

    ProductInput:
      type: object
      required: [name, price, categoryId]
      properties:
        name: { type: string }
        description: { type: string }
        price: { type: number }
        categoryId: { type: integer }

    OrderInput:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            type: object
            required: [itemId, quantity]
            properties:
              itemId: { type: integer }
              quantity: { type: integer }
