openapi: "3.0.0"
info:
  title: E-Commerce API
  version: "1.0.0"
  description: >
    REST API for an e-commerce platform with authentication, users,
    products, categories, and orders.  
    All protected routes require a valid JWT via Authorization header.

servers:
  - url: http://localhost:3000
    description: Local Development

tags:
  - name: Auth
  - name: Users
  - name: Products
  - name: Categories
  - name: Orders

paths:
  #################################
  # AUTH
  #################################
  /api/auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterInput"
      responses:
        "201":
          description: Successfully registered
        "400": 
          description: Email already exists

  /api/auth/login:
    post:
      tags: [Auth]
      summary: Login and receive a JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginInput"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid email or password

  #################################
  # USERS
  #################################
  /api/users:
    get:
      tags: [Users]
      summary: Get all users (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users
        "403":
          description: Forbidden

  /api/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema: { type: integer }
          required: true
      responses:
        "200":
          description: User found
        "404":
          description: Not found
        "403":
          description: Forbidden

  /api/users/me/profile:
    get:
      tags: [Users]
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Current user's profile

    put:
      tags: [Users]
      summary: Update current user's profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateInput"
      responses:
        "200":
          description: Updated profile

    delete:
      tags: [Users]
      summary: Delete current user's account
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Deleted

  #################################
  # PRODUCTS
  #################################
  /api/products:
    get:
      tags: [Products]
      summary: Get products (public)
      parameters:
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [id, name, price, createdAt]
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [asc, desc]
        - in: query
          name: limit
          schema: { type: integer }
        - in: query
          name: offset
          schema: { type: integer }
      responses:
        "200":
          description: List of products

    post:
      tags: [Products]
      summary: Create a product (ADMIN only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Created

  /api/products/{id}:
    get:
      tags: [Products]
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        "200":
          description: Product found
        "404":
          description: Not found

    patch:
      tags: [Products]
      summary: Update product (ADMIN only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: $ref: "#/components/schemas/ProductUpdateInput"
      responses:
        "200":
          description: Updated

    delete:
      tags: [Products]
      summary: Delete product (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Deleted

  #################################
  # CATEGORIES
  #################################
  /api/categories:
    get:
      tags: [Categories]
      summary: Get all categories
      responses:
        "200":
          description: List of categories

    post:
      tags: [Categories]
      summary: Create category (ADMIN only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: $ref: "#/components/schemas/CategoryInput"
      responses:
        "201":
          description: Created

  /api/categories/{id}:
    get:
      tags: [Categories]
      summary: Get category by ID
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        "200":
          description: Found
        "404":
          description: Not found

    put:
      tags: [Categories]
      summary: Update category (ADMIN only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: $ref: "#/components/schemas/CategoryInput"
      responses:
        "200":
          description: Updated

    delete:
      tags: [Categories]
      summary: Delete category (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Deleted

  #################################
  # ORDERS
  #################################
  /api/orders:
    get:
      tags: [Orders]
      summary: Get orders  
      description: >
        Admin: returns ALL orders  
        User: returns ONLY their own orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of orders

    post:
      tags: [Orders]
      summary: Create an order (Authenticated user)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateInput"
      responses:
        "201":
          description: Created

  /api/orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID (Admin or owner)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        "200": { description: Found }
        "403": { description: Forbidden }
        "404": { description: Not found }

    put:
      tags: [Orders]
      summary: Update order (Admin or owner)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderUpdateInput"
      responses:
        "200": { description: Updated }

    delete:
      tags: [Orders]
      summary: Delete order (Admin or owner)
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Deleted

components:
  #################################
  # SECURITY
  #################################
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  #################################
  # SCHEMAS
  #################################
  schemas:
    UserRegisterInput:
      type: object
      required: [name, email, password]
      properties:
        name: { type: string }
        email: { type: string }
        password: { type: string }

    UserLoginInput:
      type: object
      required: [email, password]
      properties:
        email: { type: string }
        password: { type: string }

    UserUpdateInput:
      type: object
      properties:
        email: { type: string }
        password: { type: string }

    CategoryInput:
      type: object
      required: [name]
      properties:
        name: { type: string }

    ProductInput:
      type: object
      required: [name, price, categoryId]
      properties:
        name: { type: string }
        price: { type: number }
        categoryId: { type: integer }
        description: { type: string }

    ProductUpdateInput:
      type: object
      properties:
        name: { type: string }
        price: { type: number }
        categoryId: { type: integer }
        description: { type: string }

    OrderCreateInput:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            type: object
            required: [itemId, quantity]
            properties:
              itemId: { type: integer }
              quantity: { type: integer }

    OrderUpdateInput:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            type: object
            required: [itemId, quantity]
            properties:
              itemId: { type: integer }
              quantity: { type: integer }
